[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]

[[bin]]
name = "hello_remote_world"
path = "main.rs"

[[bin]]
name = "ch04"
path = "ex04/examples/ch04_01_unit.rs"